### ISSUE TITLE
broken file

### ISSUE THREAD

**Issue by YiDanCheung** [oscar666123/Siamese-on-Omniglot-Dataset#1]
Hello, there. It seems that something went wrong with your jupyter notebook file(Siamese on Omniglot Dataset.ipynb). It can not be read. Can you fix it please, it means a lot to me. :grinning:

**Comment by oscar666123** [comment]
Which issue did you find? Could you tap a screenshot or describe it?

Yin-Jian Zhang ***@***.***> 于2023年6月14日周三 17:34写道：

**Comment by YiDanCheung** [comment]
Okay, here is the screenshot. 
I have downloaded the ipynb file to my own computer, and opened it with jupyter lab, it still CANNOT display normally with message "Unreadable Notebook:Siamese on Omniglot Dataset.ipynb NotJSONError('Notebook does not appear to be JSON ...')"
![issue1](https://github.com/oscar666123/Siamese-on-Omniglot-Dataset/assets/50956336/64bbb915-b84c-4092-95f0-8f3d1cf0c117)

**Comment by oscar666123** [comment]
Ok, I'll check it out.

Yin-Jian Zhang ***@***.***> 于 2023年6月15日周四 下午10:52写道：

**Comment by oscar666123** [comment]
It can be readable now.
